# -*- coding: utf-8 -*-
"""CodeDiggers.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12ziDXleFtQCLr6jfMfm4rKltPrffDqGV

# Importing Libraries
"""

import os
import numpy as np
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from google.colab import drive
drive.mount('/content/drive')

"""# Student Class"""

def LastTwoDigits(n):
    return float(str(n)[-3:]) if '.' in str(n)[-2:] else int(str(n)[-2:])

nStudents = 80

class Student():
  #Initializers
  def __init__(self):
    self.ID = -1
 
  #Setters
  def setName(self, arg1, arg2):
    self.fName = arg1
    self.lName = arg2
  def setAdmissionYear(self, arg1):
    self.Year = arg1
  def setProgram(self, arg1):
    self.Program = arg1
  def setRegNumber(self, arg1):
    self.regNumber = arg1

  def AddStudent(self, FirstNam, LastNam, AdmYear, Progr, regNo):
    self.fName = FirstNam
    self.lName = LastNam
    self.Year = AdmYear
    self.Program = Progr
    self.regNumber = str(regNo)
    if len(str(regNo))==1:
      self.ID = self.Program + str(LastTwoDigits(self.Year)) +'00'+self.regNumber
    else:
      self.ID = self.Program + str(LastTwoDigits(self.Year)) +'0'+self.regNumber

  #Getters
  def getID(self):
	  return self.ID
  def getName(self):
	  return ('self.fName + self.lName')
  def getProgram(self):
	  return self.Program
  def getYear(self):
	  return self.Year

  #Functions
  def displayStudent(self):
    if self.ID != -1:
      print("STUDENT DETAILS: ", '\n', "- NAME : ", self.fName, self.lName, '\n', "- ID   : ", self.ID, '\n')

def searchStudent(S, reg):
  for i in range(0,nStudents):
    if (S[i].getID() == str(reg)):
      return True
    else:
      return False

def TotalStudents(S):
	counter = 0;
	for i in range(0,nStudents):
		if (S[i].getID() != -1):
			counter=counter+1
	return counter

"""# UI

Initialize Class Array
"""

BSEE = [Student() for i in range(80)]
result = []
countReg = 1

print('Welcome to STUDENT FACILITATION PORTAl \n')
while 1:
  os.system('cls')
  temp = input("1: LOG IN \n2: SIGN UP (ADMIN ONLY) \n3: EXIT\n")
  if temp.isdigit():
    if int(temp) == 1:
      string = input("Registration Number: ")
      if searchStudent(BSEE, string):
        print("\nUser Found!\n")
        option = input("1: TRANSCRIPT\n2: STUDENT LOAN \n3: GO BACK\n")
        if option.isdigit():
          if int(option) == 1:
            print("TRANSCRIPT LOADING...\n")
            #DISPLAY TRANSCRIPT!!
            print("WE CAN NOW LOAD TRASNCRIPT FROM A CSV FILE...\n")

          elif int(option) == 2:
            print("\nSTUDENT LOAN PORTAL:")
            money = int(input("AMOUNT (PKR): "))
            reason = input("STATE THE REASON OF APPLYING FOR STUDENT LOAN: ")
            loan = '\n'+string+' has applied for a loan of '+str(money)+ ' due to the following reason: \n'+reason
            print(loan,'\n')
            print('Your request has been sent to the Administration! \nPlease wait for their reply!\n')
            
            #SEND EMAIL TO ADMIN!!
            '''
            EMAIL_ADDRESS = 'mfarooqhammad@gmail.com'
            PASSWORD = 'nopass'
            s = smtplib.SMTP(host='admin@university.edu.pk', port=587)
            s.starttls()
            s.login(EMAIL_ADDRESS, PASSWORD)
            msg = MIMEMultipart()
            message = message_template.substitute(PERSON_NAME=admin@university.edu.pk)
            msg['From']=EMAIL_ADDRESS
            msg['To']='admin@university.edu.pk'
            msg['Subject']=loan
            msg.attach(MIMEText(message, 'plain'))
            s.send_message(msg)
            del msg
            '''

          elif int(option) == 3: 
            continue
          else:
            print("Invalid Input!")
        else:
          print('\nInvalid Input! \nPlease enter an Integer..\n')
      else:
        print("\nNo User Found!\n")
    elif int(temp) == 2:
      passw = int(input("ADMIN PASSWORD: "))
      if passw == 12345:
        FName = input("First Name: ")
        LName = input("Last Name: ")
        Year = int(input("Year of Admission: "))
        Degree = input("Degree Program: ")
        BSEE[TotalStudents(BSEE)].AddStudent(FName, LName, Year, Degree, countReg)
        print('\nYour Registration Number is: ', BSEE[TotalStudents(BSEE)-1].ID, '\n-SIGNED UP Sucessfully!\n')
        tempStr = FName+' '+LName+' - '+str(Year)+' - '+Degree+' - '+BSEE[TotalStudents(BSEE)-1].ID
        result.insert(TotalStudents(BSEE)-1, tempStr)
        print(result,'\n')
        #np.savetxt('/content/drive/MyDrive/Colab Notebooks/CodeDiggers/StudentInfo.csv', result, delimiter=',')
        countReg = countReg+1
      else:
        print('Wrong Password! \nTry again..\n')
    elif int(temp) == 3:
      print("\nHave a Good Day!\n")
      break
    else:
      print('\nInvalid Input! \nTry again..\n')
  else:
    print('\nInvalid Input! \nPlease enter an Integer..\n')

for i in range(0,nStudents):
  BSEE[i].displayStudent()